# .github/workflows/health_check.yml
name: Website Health Check

on:
  schedule:
    # 每 10 分钟运行一次
    - cron: '*/10 * * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  check:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 运行环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 检出你的仓库代码

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # 使用 Python 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # 安装 requirements.txt 中定义的库

      - name: Run health check script
        env:
          # 从 GitHub Secrets 读取敏感信息并设置为环境变量
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python check_availability.py # 运行 Python 脚本
